- hosts: all
  remote_user: "{{ansible_user}}"
  gather_facts: True
  become: yes

  pre_tasks:
    - name: Add EPEL repository for Centos/Rocky
      package:
        name: epel-release
        state: latest
        #      when: ansible_facts['os_family'] == 'RedHat'
      when:
        ansible_distribution in ['RedHat', 'CentOS', 'ScientificLinux', 'OracleLinux']
        and (ansible_distribution_major_version is version('7', '=')
        or ansible_distribution_major_version is version('8', '='))

  roles:
    - { role: install-netdata-repository, become: yes }
    - { role: install-netdata-agent, become: yes }
