---

# Suse

- name: Add repo and install package
  block:

    - name: Install dependencies
      community.general.zypper:
        name: libnetfilter_acct1
        state: present
      when: ansible_distribution_major_version is version('16', '<')

    - name: Set repository version path
      ansible.builtin.set_fact:
        netdata_opensuse_releasever: >-
          {{ 'tumbleweed' if 'tumbleweed' in ansible_facts.distribution | lower
          else '$releasever' }}

    - name: Import Netdata GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ netdata_repository_key_url }}"

    - name: Add repository
      community.general.zypper_repository:
        name: "netdata"
        repo: "{{ netdata_repository_url }}{{ netdata_release_channel_normalized }}/opensuse/{{ netdata_opensuse_releasever }}/$basearch"
        state: present
        auto_import_keys: true

    - name: Add repository configuration
      community.general.zypper_repository:
        name: "netdata-repoconfig"
        repo: "{{ netdata_repository_url }}{{ netdata_release_channel_normalized }}/opensuse/{{ netdata_opensuse_releasever }}/$basearch"
        state: present
        auto_import_keys: true

    - name: Install package
      community.general.zypper:
        name: netdata
        state: present
        disable_recommends: false
      notify: Restart Netdata

    - name: Install chart support if enabled
      community.general.zypper:
        name: netdata-plugin-chartsd
        state: present
      notify: Restart Netdata
      when: netdata_manage_charts
