---
# Set the EL prefix, used for repo baseurls e.g.
# https://repository.netdata.cloud/repos/stable/el/9/$basearch
#                                               ^^----- This bit right here
- name: "Set netdata_el_repo_distro (Enterprise Linux)"
  ansible.builtin.set_fact:
    netdata_el_repo_distro: el

- name: "Set netdata_el_repo_distro (Oracle Linux)"
  ansible.builtin.set_fact:
    netdata_el_repo_distro: ol
  when: ansible_facts['distribution'] == "OracleLinux"

- name: "Set netdata_el_repo_distro (Fedora)"
  ansible.builtin.set_fact:
    netdata_el_repo_distro: fedora
  when: ansible_facts['distribution'] == "Fedora"

- name: "Set netdata_el_repo_distro (Amazon Linux)"
  ansible.builtin.set_fact:
    netdata_el_repo_distro: amazonlinux
  when: ansible_facts['distribution'] == "Amazon"

- name: "Ensure netdata repo keys are present"
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - "{{ netdata_repository_key_url }}"
    - "{{ netdata_repository_old_key_url }}"
  notify:
    - "Update dnf cache"

- name: "Ensure netdata repository is configured: {{ netdata_release_channel_normalized }}"
  ansible.builtin.yum_repository:
    baseurl: "{{ netdata_repository_url }}{{ netdata_release_channel_normalized }}/{{ netdata_el_repo_distro }}/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/"
    description: Netdata {{ netdata_release_channel_normalized }}
    state: present
    enabled: true
    file: netdata-{{ netdata_release_channel_normalized }}
    gpgcheck: true
    gpgkey:
      - "{{ netdata_repository_key_url }}"
      - "{{ netdata_repository_old_key_url }}"
    name: netdata-{{ netdata_release_channel_normalized }}
    priority: 50
    repo_gpgcheck: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    sslverify: true
  notify:
    - "Update dnf cache"

- name: "Ensure netdata is installed"
  ansible.builtin.dnf:
    name:
      - util-linux
      - openssl
      - netdata
    state: present
    update_cache: true

- name: Install chart support if enabled
  ansible.builtin.dnf:
    name: "netdata-plugin-chartsd"
    state: present
  notify: Restart Netdata
  when: netdata_manage_charts
...