---

- name: Create node claim file
  ansible.builtin.template:
    src: claim.conf.j2
    dest: "{{ netdata_config_dir }}/claim.conf"
    owner: "{{ netdata_config_owner }}"
    group: "{{ netdata_config_group }}"
    mode: '0640'
  notify: Reload Netdata claiming state
