---
# tasks file for roles/purge_netdata_agent

- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"

- name: Include OS specific install
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
