# -*- mode: ruby -*-
# vi: set ft=ruby :

pscript = <<-SHELL
    dnf update -y
    dnf install -y zlib-devel libuuid-devel libuv-devel lz4-devel Judy-devel openssl-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils python cmake json-c-devel
  SHELL

pscript << File.open("../common-provision.sh").read

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "fedora/31-cloud-base"
  config.vm.hostname = "loki-fedora31-vm"
  config.vm.network "forwarded_port", guest: 19999, host: 20004

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "shell", inline: pscript
end
