# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url | lower }}/{{ item.image | lower }}
{% else %}
FROM {{ item.image | lower }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN apt update && \
	apt install -y nano curl gpg-agent
