FROM {{ item.image | lower }}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
                apt-utils \
                curl \
                debian-archive-keyring \
                gpg-agent \
                gnupg \
                nano \
                python3 \
                software-properties-common \
                && apt-get clean \
                && rm -Rf /var/lib/apt/lists/* \
                && rm -Rf /usr/share/doc \
                && rm -Rf /usr/share/man
