---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker

platforms:

  - name: centos7
    image: quay.io/centos/centos:7
    pre_build_image: true

  - name: Debian10
    image: debian:10
    pre_build_image: false
    dockerfile: ../common/Dockerfile_debian10.j2

  - name: debian11
    image: debian:11
    pre_build_image: false
    dockerfile: ../common/Dockerfile_debian11.j2

  - name: fedora35
    image: fedora:35
    pre_build_image: true

  - name: oraclelinux8
    image: oraclelinux:8
    pre_build_image: true

  - name: rockylinux8
    image: rockylinux:8
    pre_build_image: true

  - name: ubuntu1804
    image: ubuntu:18.04
    dockerfile: ../common/Dockerfile_ubuntu1804.j2
    entrypoint: "/usr/bin/bash"
    pre_build_image: false

  - name: ubuntu2004
    image: ubuntu:20.04
    dockerfile: ../common/Dockerfile_ubuntu2004.j2
    entrypoint: "/usr/bin/bash"
    pre_build_image: false

  - name: ubuntu2204
    image: ubuntu:22.04
    dockerfile: ../common/Dockerfile_ubuntu2204.j2
    entrypoint: "/usr/bin/bash"
    pre_build_image: false


provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: false

verifier:
  name: ansible
