---

- name: Remove Netdata repo key.
  ansible.builtin.apt_key:
    url: https://packagecloud.io/netdata/netdata-repoconfig/gpgkey
    state: absent

- name: Remove Netdata packages
  ansible.builtin.apt:
    state: absent
    purge: true
    name:
      - netdata
      - netdata-repo
      - netdata-repo-edge

- name: Remove the remains
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
