---

- name: Install Netdata repo key.
  ansible.builtin.apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey
    state: present

- name: Install netdata repo
  ansible.builtin.apt:
    deb: "{{ repo_uri }}"
