---
- name: Install uuid-runtime
  ansible.builtin.package:
    name: uuid-runtime
    state: present

- name: Install the netdata agent package
  ansible.builtin.apt:
    name: netdata
    update_cache: true
    state: latest
    # default_release:

- name: Start service "{{ netdata_agent_service }}"
  ansible.builtin.systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: true
    masked: false
