---
# tasks file for roles/install_netdata_agent

- name: Include architecture specific vars
  ansible.builtin.include_vars: "{{ ansible_architecture | lower }}.yml"

- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"

- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
