---

# We have to install the dependencies from EPEL because we have to disable it when installing netdata agent.

- name: Dependencies first
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - Judy
    - brotli
    - libuv
    - netcat
    - nodejs
    - nodejs-libs
    - openssl11
    - yum-plugin-priorities

# We disabled EPEL for netdata agent installation to exclude the possibility of installing EPEL package
- package:
    name: "{{ netdata_agent_package }}"
    state: latest
    update_cache: True
    disable_gpg_check: True
    disablerepo: "epel"

- name: Writing configuration to /etc/netdata/netdata.conf
  ansible.builtin.template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart netdata agent

- name: Start "{{ netdata_agent_service }}" service
  systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: True
